# Generated by Django 4.2.5 on 2023-10-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_prediction_doctor_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default=' ', max_length=25, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='username',
            field=models.CharField(default=' ', max_length=25, verbose_name='username'),
        ),
    ]
